#!/usr/bin/env bash
set -euo pipefail

TMP_FILES=()
cleanup() {
  for f in "${TMP_FILES[@]}"; do
    [ -f "$f" ] && rm -f "$f"
  done
}
trap cleanup EXIT

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# 输入（本地 mihomo domain rule-set）
IN_AIGC="compilation/mihomo/AIGC.yaml"
IN_DIRECT="compilation/mihomo/Direct.yaml"
IN_PROXY="compilation/mihomo/Proxy.yaml"

# 输出（Shadowrocket domain list）
OUT_AIGC="compilation/shadowrocket/AIGC.list"
OUT_DIRECT="compilation/shadowrocket/Direct.list"
OUT_PROXY="compilation/shadowrocket/Proxy.list"

# 输入（远程 mihomo geoip ip rule-set）
URL_TELEGRAM="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml"
URL_GOOGLE="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml"
URL_CN="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml"

# 输出（Shadowrocket geoip list）
OUT_GEO_TELEGRAM="compilation/shadowrocket/geoip-telegram.list"
OUT_GEO_GOOGLE="compilation/shadowrocket/geoip-google.list"
OUT_GEO_CN="compilation/shadowrocket/geoip-cn.list"

mkdir -p "compilation/shadowrocket"

PYTHON_BIN="${PYTHON_BIN:-python3}"

# 解析 mihomo/clash rule-set YAML，取出 payload / rules / domains 等常见字段
# 并将 domain 规则转为 Shadowrocket 格式：
# - "+.example.com" => "DOMAIN-SUFFIX,example.com"
# - "example.com"   => "DOMAIN-SUFFIX,example.com"（按最常用习惯处理；如你希望用 DOMAIN，请改下面逻辑）
convert_domain_yaml_to_shadowrocket_list() {
  local in_file="$1"
  local out_file="$2"

  "$PYTHON_BIN" - <<'PY' "$in_file" "$out_file"
import sys, re, pathlib

inp = pathlib.Path(sys.argv[1])
outp = pathlib.Path(sys.argv[2])

try:
    import yaml
except Exception as e:
    print("PyYAML not installed:", e, file=sys.stderr)
    sys.exit(2)

data = yaml.safe_load(inp.read_text(encoding="utf-8")) if inp.exists() else None
if data is None:
    payload = []
elif isinstance(data, dict):
    # 常见：payload: [...]
    if isinstance(data.get("payload"), list):
        payload = data["payload"]
    elif isinstance(data.get("rules"), list):
        payload = data["rules"]
    elif isinstance(data.get("domains"), list):
        payload = data["domains"]
    else:
        # 兜底：如果整个 dict 不符合预期
        payload = []
elif isinstance(data, list):
    payload = data
else:
    payload = []

def norm_line(x: str) -> str:
    x = x.strip()
    # 去掉可能的引号
    if (x.startswith('"') and x.endswith('"')) or (x.startswith("'") and x.endswith("'")):
        x = x[1:-1].strip()
    return x

lines = []
seen = set()

for item in payload:
    if item is None:
        continue
    s = norm_line(str(item))
    if not s or s.startswith("#"):
        continue

    # mihomo/clash 规则集中常见写法：+.domain.tld 表示 domain-suffix
    if s.startswith("+."):
        dom = s[2:].strip()
        rule = f"DOMAIN-SUFFIX,{dom}"
    else:
        # 你说明“内容为domain”，这里统一按 DOMAIN-SUFFIX 输出以兼容常见场景
        # 如你确认是精确域名列表，把下面一行改为：rule = f"DOMAIN,{s}"
        rule = f"DOMAIN-SUFFIX,{s}"

    if rule not in seen:
        seen.add(rule)
        lines.append(rule)

    if rule not in seen:
        seen.add(rule)
        lines.append(rule)

# 不排序，保持原始顺序（同时去重保留第一次出现）
header = [
    "# Generated by GitHub Actions",
    "# Source: mihomo rule-set (domain) yaml -> Shadowrocket .list",
]
outp.write_text("\n".join(header + lines) + "\n", encoding="utf-8")

# 下载远程 yaml 后解析为 IP-CIDR / IP-CIDR6（Shadowrocket 格式）
convert_geoip_yaml_url_to_shadowrocket_list() {
  local url="$1"
  local out_file="$2"
  local tmp_yaml
  tmp_yaml="$(mktemp)"
  TMP_FILES+=("$tmp_yaml")

  curl -fsSL "$url" -o "$tmp_yaml"

  "$PYTHON_BIN" - <<'PY' "$tmp_yaml" "$out_file" "$url"
import sys, ipaddress, pathlib

inp = pathlib.Path(sys.argv[1])
outp = pathlib.Path(sys.argv[2])
src_url = sys.argv[3]

try:
    import yaml
except Exception as e:
    print("PyYAML not installed:", e, file=sys.stderr)
    sys.exit(2)

data = yaml.safe_load(inp.read_text(encoding="utf-8"))
if data is None:
    payload = []
elif isinstance(data, dict):
    if isinstance(data.get("payload"), list):
        payload = data["payload"]
    elif isinstance(data.get("rules"), list):
        payload = data["rules"]
    else:
        payload = []
elif isinstance(data, list):
    payload = data
else:
    payload = []

def norm_line(x: str) -> str:
    x = x.strip()
    if (x.startswith('"') and x.endswith('"')) or (x.startswith("'") and x.endswith("'")):
        x = x[1:-1].strip()
    return x

lines = []
seen = set()

for item in payload:
    if item is None:
        continue
    s = norm_line(str(item))
    if not s or s.startswith("#"):
        continue

    # 有些数据可能带 no-resolve 或其他后缀，这里只取 CIDR 主体
    cidr = s.split(",")[0].strip()

    try:
        net = ipaddress.ip_network(cidr, strict=False)
    except Exception:
        # 跳过非 CIDR
        continue

    if net.version == 6:
        rule = f"IP-CIDR6,{net.compressed},no-resolve"
    else:
        rule = f"IP-CIDR,{net.compressed},no-resolve"

    if rule not in seen:
        seen.add(rule)
        lines.append(rule)

    if rule not in seen:
        seen.add(rule)
        lines.append(rule)

# 不排序，保持原始顺序（同时去重保留第一次出现）
header = [
    "# Generated by GitHub Actions",
    f"# Source: {src_url}",
    "# Source: mihomo rule-set (geoip/ip) yaml -> Shadowrocket .list",
]
outp.write_text("\n".join(header + lines) + "\n", encoding="utf-8")


echo "[1/2] Convert local domain rule-sets..."
convert_domain_yaml_to_shadowrocket_list "$IN_AIGC"   "$OUT_AIGC"
convert_domain_yaml_to_shadowrocket_list "$IN_DIRECT" "$OUT_DIRECT"
convert_domain_yaml_to_shadowrocket_list "$IN_PROXY"  "$OUT_PROXY"

echo "[2/2] Download & convert remote geoip (ip) rule-sets..."
convert_geoip_yaml_url_to_shadowrocket_list "$URL_TELEGRAM" "$OUT_GEO_TELEGRAM"
convert_geoip_yaml_url_to_shadowrocket_list "$URL_GOOGLE"   "$OUT_GEO_GOOGLE"
convert_geoip_yaml_url_to_shadowrocket_list "$URL_CN"       "$OUT_GEO_CN"

echo "Done."
