payload:
  - github-api.arkoselabs.com
  - github-cloud.s3.amazonaws.com
  - +.githubhackathon.com
  - +.git.io
  - +.atom.io
  - +.ghcr.io
  - +.githubnext.com
  - +.github.ai
  - +.github.blog
  - +.github.com
  - +.github.community
  - +.github.dev
  - +.github.io
  - +.githubpreview.dev
  - +.githubassets.com
  - +.githubcopilot.com
  - +.gh.io
  - +.dependabot.com
  - +.githubapp.com
  - +.githubstatus.com
  - +.githubuniverse.com
  - +.githubusercontent.com
  - +.myoctocat.com
  - +.octocaptcha.com
  - +.opensource.guide
  - +.repo.new
  - +.thegithubshop.com
  - +.npmjs.org
  - +.npm.community
  - +.npmjs.com
  - +.blob.core.windows.net
  - +.collector.github.com
  - +.copilot-telemetry.githubusercontent.com
  - cdn.jsdelivr.net
  - +.jsdelivr.com
  - +.jsdelivr.net
  - +.esm.run
  - developers.facebook.com
  - notary-submissions-prod.s3-accelerate.amazonaws.com
  - notary-submissions-prod.s3.us-west-2.amazonaws.com
  - appleworldwidedeveloper.hb-api.omtrdc.net
  - appleworldwidedeveloper.sc.omtrdc.net
  - p-events-delivery.akamaized.net
  - d29vzk4ow07wi7.cloudfront.net
  - docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com
  - docker-pinata-support.s3.amazonaws.com
  - homebrew.bintray.com
  - amp.akamaized.net
  - android.googlesource.com
  - gitlab-assets.oss-cn-hongkong.aliyuncs.com
  - az764295.vo.msecnd.net
  - bingsettingssearch.trafficmanager.net
  - default.exp-tas.com
  - developer.microsoft.com
  - download.visualstudio.microsoft.com
  - dtlgalleryint.cloudapp.net
  - poshtestgallery.cloudapp.net
  - psg-int-centralus.cloudapp.net
  - psg-int-eastus.cloudapp.net
  - rink.hockeyapp.net
  - vscode-sync-insiders.trafficmanager.net
  - vscode-sync.trafficmanager.net
  - vscode.blob.core.windows.net
  - vscode.search.windows.net
  - vsmarketplacebadge.apphb.com
  - firebase.google.com
  - firebase.googleapis.com
  - firebaseappcheck.googleapis.com
  - firebasedynamiclinks-ipv4.googleapis.com
  - firebasedynamiclinks-ipv6.googleapis.com
  - firebasedynamiclinks.googleapis.com
  - firebaseinappmessaging.googleapis.com
  - firebaseinstallations.googleapis.com
  - firebaselogging-pa.googleapis.com
  - firebaselogging.googleapis.com
  - firebaseperusertopics-pa.googleapis.com
  - firebaseremoteconfig.googleapis.com
  - +.android
  - +.java
  - +.componentkit.org
  - +.badgen.net
  - +.bitvise.com
  - +.cdnjs.com
  - +.centos.org
  - +.chocolatey.org
  - +.clojure.org
  - +.cnpmjs.org
  - +.cygwin.com
  - +.cython.org
  - +.deno.com
  - +.deno.land
  - +.dev.to
  - +.elixir-lang.org
  - +.elrepo.org
  - +.erlang.org
  - +.ffmpeg.org
  - +.freebsd.org
  - +.gentoo.org
  - +.getcomposer.org
  - +.getzola.org
  - +.git-scm.com
  - +.gnu.org
  - +.godbolt.org
  - +.hex.pm
  - +.hexdocs.pm
  - +.imageglass.org
  - +.ius.io
  - +.jenkins.io
  - +.js.org
  - +.jupyter.org
  - +.kali.org
  - +.linuxfromscratch.org
  - +.linuxmint.com
  - +.lua.org
  - +.macports.org
  - +.mariadb.org
  - +.mingw.org
  - +.mobatek.net
  - +.mpv.io
  - +.mysql.com
  - +.neovim.io
  - +.netfilter.org
  - +.newpipe.net
  - +.nftables.org
  - +.nixos.org
  - +.nodesource.com
  - +.notepad-plus-plus.org
  - +.openresty.org
  - +.openssl.org
  - +.opensuse.org
  - +.packagist.org
  - +.pcre.org
  - +.phantomjs.org
  - +.php.net
  - +.postgresql.org
  - +.putty.org
  - +.r-project.org
  - +.raspberrypi.org
  - +.raspbian.org
  - +.regex101.com
  - +.rpmfusion.org
  - +.scientificlinux.org
  - +.scoop.sh
  - +.shellcheck.net
  - +.shields.io
  - +.sqlite.org
  - +.sublimetext.com
  - +.tampermonkey.net
  - +.termius.com
  - +.unpkg.com
  - +.videojs.com
  - +.videolan.org
  - +.wapm.io
  - +.wasmer.io
  - +.webflow.com
  - +.weblate.org
  - +.wireshark.org
  - +.x.org
  - +.xposed.info
  - +.yarnpkg.com
  - +.zsh.org
  - +.zed.dev
  - +.anaconda.cloud
  - +.anaconda.com
  - +.anaconda.org
  - +.conda.io
  - +.framer.com
  - +.framer.website
  - +.framercanvas.com
  - +.framerstatic.com
  - +.framerusercontent.com
  - +.mystrikingly.com
  - +.strikingly.com
  - +.strikinglycdn.com
  - +.accountkit.com
  - +.atscaleconference.com
  - +.botorch.org
  - +.buck.build
  - +.buckbuild.com
  - +.draftjs.org
  - +.f8.com
  - +.facebookappcenter.info
  - +.facebookappcenter.net
  - +.facebookappcenter.org
  - +.facebookconnect.com
  - +.facebookdevelopergarage.com
  - +.faciometrics.com
  - +.fasttext.cc
  - +.fbf8.com
  - +.fbinfer.com
  - +.fblitho.com
  - +.fbredex.com
  - +.fbrell.com
  - +.flow.dev
  - +.flow.org
  - +.flowtype.org
  - +.frescolib.org
  - +.hacklang.org
  - +.hhvm.com
  - +.makeitopen.com
  - +.mcrouter.net
  - +.mcrouter.org
  - +.messengerdevelopers.com
  - +.ogp.me
  - +.opengraphprotocol.com
  - +.opengraphprotocol.org
  - +.parse.com
  - +.pyrobot.org
  - +.react.com
  - +.reactjs.com
  - +.reactjs.org
  - +.recoiljs.org
  - +.rocksdb.com
  - +.rocksdb.net
  - +.rocksdb.org
  - +.yogalayout.com
  - +.scala-lang.org
  - +.scala-sbt.org
  - +.macruby.com
  - +.cups.org
  - +.macruby.net
  - +.swift.org
  - +.appleswift.com
  - +.webobjects.com
  - +.wpewebkit.org
  - +.calendarserver.org
  - +.macruby.org
  - +.macosforge.org
  - +.servicetalk.io
  - +.apple-cloudkit.com
  - +.foundationdb.org
  - +.apple-mapkit.com
  - +.webkitgtk.org
  - +.carekit.org
  - +.researchandcare.org
  - +.researchkit.hk
  - +.researchkit.net
  - +.researchkit.org
  - +.researchkit.tv
  - +.webkit.org
  - +.canonical.com
  - +.launchpad.net
  - +.launchpadcontent.net
  - +.launchpadlibrarian.com
  - +.unity3d.com
  - +.unity.com
  - +.docs.rs
  - +.launchpadlibrarian.net
  - +.launchpadlibrarian.org
  - +.snapcraft.io
  - +.snapstore.io
  - +.ubuntu.com
  - +.ubuntu.net
  - +.ubuntuforums.org
  - +.ubuntu-touch.io
  - +.flutter.dev
  - +.flutterapp.com
  - +.pub.dev
  - +.polymer-project.org
  - +.polymerproject.org
  - +.archlinux.org
  - +.archlinuxarm.org
  - +.archlinuxcn.org
  - +.embed.ly
  - +.embedly.com
  - +.playerjs.io
  - +.fury.blog
  - +.fury.co
  - +.fury.dev
  - +.fury.help
  - +.fury.io
  - +.gemfury.com
  - +.gitbook.com
  - +.gitbook.io
  - +.ruby-lang.org
  - +.rubygems.org
  - +.jfrog.com
  - +.jfrog.org
  - +.bintray.com
  - +.perl.org
  - +.cpan.org
  - +.metacpan.org
  - +.modperl.pl
  - +.crates.io
  - +.rustup.rs
  - +.rust-lang.org
  - +.pythonhosted.org
  - +.python.org
  - +.readthedocs-hosted.com
  - +.readthedocs.com
  - +.readthedocs.io
  - +.readthedocs.org
  - +.bootstrapcdn.com
  - +.getbootstrap.com
  - +.compose-spec.io
  - +.docker.com
  - +.docker.io
  - +.dockerstatic.com
  - +.fontawesome.com
  - +.fortawesome.com
  - +.artixlinux.org
  - +.adventofcode.com
  - +.pypi.org
  - +.brew.sh
  - +.sourcehut.org
  - +.sr.ht
  - +.dart.dev
  - +.dartlang.org
  - +.dartpad.dev
  - +.lfai.foundation
  - +.linuxfoundation.org
  - +.kernel.org
  - +.linux.org
  - +.openjsf.org
  - +.amp.dev
  - +.ampproject.com
  - +.ampproject.net
  - +.ampproject.org
  - +.electronjs.org
  - +.jquery.com
  - +.jquerymobile.com
  - +.jqueryui.com
  - +.mochajs.org
  - +.nodejs.org
  - +.braventures.com
  - +.braveux.com
  - +.compass.is
  - +.fightforux.com
  - +.forthebadge.com
  - +.stockagainstphotography.com
  - +.haskell.org
  - +.haskellstack.org
  - +.stackage.org
  - +.redhat.com
  - +.redhat.org
  - +.v8.dev
  - +.v8project.org
  - +.debian.org
  - +.dotdeb.org
  - +.openwrt.org
  - +.lede-project.org
  - +.osdn.net
  - +.01.org
  - +.hyperscan.io
  - +.intellinuxgraphics.com
  - +.intellinuxgraphics.net
  - +.oneapi.com
  - +.oneapi.io
  - +.opencas.io
  - +.opendroneid.org
  - +.openvino.ai
  - +.openvinotoolkit.org
  - +.renderingtoolkit.org
  - +.snap-telemetry.io
  - +.universalscalablefirmware.org
  - +.acpica.com
  - +.clearlinux.org
  - +.ospray.net
  - +.ospray.org
  - +.intellij.com
  - +.intellij.net
  - +.intellij.org
  - +.jetbrains.com
  - +.jetbrains.net
  - +.jetbrains.space
  - +.jetbrains.team
  - +.datalore.io
  - +.kotlinlang.org
  - +.jb.gg
  - +.youtrack.cloud
  - +.topcoder.com
  - +.azurecr.io
  - +.ecr.aws
  - +.gcr.io
  - +.quay.io
  - +.pypi.io
  - +.pypa.io
  - +.pycon.org
  - +.consul.io
  - +.hashicorp.com
  - +.nomadproject.io
  - +.packer.io
  - +.terraform.io
  - +.vagrantcloud.com
  - +.vagrantup.com
  - +.vaultproject.io
  - +.grazie.ai
  - +.jetbrains.ai
  - +.sentry.io
  - +.sentry-cdn.com
  - +.termux.com
  - +.termux.dev
  - +.termux.org
  - +.apache.org
  - +.android.com
  - +.androidify.com
  - +.flathub.org
  - +.flatpak.org
  - +.gitlab.com
  - +.gitlab.io
  - +.gitlab.net
  - +.gitlab-static.net
  - +.alpinelinux.org
  - +.java.com
  - +.java.net
  - +.getfedora.org
  - +.fedoraforum.org
  - +.fedorapeople.org
  - +.fedoraproject.org
  - +.fedoramagazine.org
  - +.nginx.com
  - +.nginx.org
  - +.redis.io
  - +.redislabs.com
  - +.remirepo.net
  - +.vim.org
  - +.codeberg.org
  - +.codeberg.page
  - +.kubernetes.io
  - +.k8s.io
  - +.mongodb.com
  - +.mongodb.org
  - +.piwheels.org
  - +.qt.io
  - +.qt-project.org
  - +.github1s.com
  - +.sourcegraph.com
  - +.adaptivecards.io
  - +.api-extractor.com
  - +.apisof.net
  - +.appcenter.ms
  - +.blazor.net
  - +.botframework.com
  - +.codethemicrobit.com
  - +.devopsassessment.net
  - +.dot.net
  - +.gamesstack.com
  - +.graphengine.io
  - +.insiderdevtour.com
  - +.jwt.ms
  - +.microbit.org
  - +.microsoftadc.com
  - +.microsoftgamestack.com
  - +.microsoftiotinsiderlabs.com
  - +.microsoftreactor.info
  - +.microsoftreactor.net
  - +.microsoftreactor.org
  - +.microsoftsilverlight.com
  - +.microsoftsilverlight.org
  - +.microsoftsilverlight.net
  - +.microsoftsqlserver.com
  - +.mmdnn.com
  - +.mono-project.com
  - +.msdn.com
  - +.msinnovationchallenge.com
  - +.mspairlift.com
  - +.msropendata.com
  - +.nuget.org
  - +.nugettest.org
  - +.opentranslatorstothings.org
  - +.poshtestgallery.com
  - +.pwabuilder.com
  - +.sankie.net
  - +.sqlserveronlinux.com
  - +.timelinestoryteller.com
  - +.uwpcommunitytoolkit.com
  - +.visualstudio-staging.com
  - +.visualstudio.com
  - +.visualstudio.co
  - +.visualstudio.eu
  - +.visualstudio.net
  - +.vfsforgit.com
  - +.vfsforgit.org
  - +.vsassets.io
  - +.vscode.dev
  - +.vscode-cdn.net
  - +.vscode-unpkg.net
  - +.xamarin.com
  - +.firebase.com
  - +.firebase.io
  - +.firebaseapp.com
  - +.firebaseio.com
  - +.go-lang.com
  - +.go-lang.net
  - +.go-lang.org
  - +.go.dev
  - +.godoc.org
  - +.golang.com
  - +.golang.net
  - +.golang.org
  - +.askubuntu.com
  - +.blogoverflow.com
  - +.codeforaliving.io
  - +.mathoverflow.net
  - +.serverfault.com
  - +.sstatic.net
  - +.stackapps.com
  - +.stackauth.com
  - +.stackexchange.com
  - +.stackmod.blog
  - +.stackoverflow.blog
  - +.stackoverflow.co
  - +.stackoverflow.com
  - +.stackoverflow.email
  - +.stackoverflow.help
  - +.stackoverflow.net
  - +.stackoverflowbusiness.com
  - +.stackoverflowcareers.com
  - +.stackoverflowjobs.com
  - +.stackoverflowsolutions.com
  - +.stackoverflowteams.com
  - +.stacksnippets.net
  - +.superuser.com
  - +.tex-talk.net
  - +.thesffblog.com
  - +.fastlane.ci
  - +.fastlane.tools
  - +.developer.apple.com
  - +.mcr.microsoft.com
  - +.visualstudio.co.uk
  - +.greenend.org.uk
  - +.timestamp.apple.com
  - +.developerservices2.apple.com
  - +.devstreaming-cdn.apple.com
  - +.devimages-cdn.apple.com
  - +.playgrounds-cdn.apple.com
  - +.researchkit.cn
  - +.researchkit.com.cn
  - +.swiftui.cn
  - +.swiftui.com.cn
  - cdn.ampproject.org
  - +.cdn.jetbrains.com
  - +.download-cdn.jetbrains.com.cn
  - +.microsoftreactor.cn
  - +.microsoftreactor.com.cn
  - +.reactorms.com.cn
  - firebase-settings.crashlytics.com
  - +.ads.unitychina.cn
  - +.splash-ads.cdn.unity.cn
  - +.splash-ads.unitychina.cn
  - +.unityads.unity.cn
  - +.unityads.unity3d.com
  - +.unityads.unitychina.cn
  - +.b-cdn.net
  - +.bunny.net
  - +.bunnycdn.com
  - +.argotunnel.com
  - +.browser.run
  - +.cfargotunnel.com
  - +.cfdata.org
  - +.cfl.re
  - +.cloudflare-dns.com
  - +.cloudflare-ech.com
  - +.cloudflare-esni.com
  - +.cloudflare-gateway.com
  - +.cloudflare-quic.com
  - +.cloudflare-terms-of-service-abuse.com
  - +.cloudflare.com
  - +.cloudflare.dev
  - +.cloudflare.net
  - +.cloudflare.tv
  - +.cloudflareaccess.com
  - +.cloudflareapps.com
  - +.cloudflarebolt.com
  - +.cloudflarebrowser.com
  - +.cloudflarechallenge.com
  - +.cloudflareclient.com
  - +.cloudflarecp.com
  - +.cloudflareinsights.com
  - +.cloudflareok.com
  - +.cloudflarepartners.com
  - +.cloudflareportal.com
  - +.cloudflarepreview.com
  - +.cloudflareregistrar.com
  - +.cloudflareresearch.com
  - +.cloudflareresolve.com
  - +.cloudflaressl.com
  - +.cloudflarestatus.com
  - +.cloudflarestorage.com
  - +.cloudflarestream.com
  - +.cloudflaresupport.com
  - +.cloudflaretest.com
  - +.cloudflarewarp.com
  - +.cloudflareworkers.com
  - +.encryptedsni.com
  - +.every1dns.net
  - +.imagedelivery.net
  - +.isbgpsafeyet.com
  - +.pacloudflare.com
  - +.pages.dev
  - +.r2.dev
  - +.trycloudflare.com
  - +.videodelivery.net
  - +.warp.plus
  - +.workers.dev
  - +.cf-ipfs.com
  - +.cloudflare-ipfs.com
  - +.delvenetworks.com
  - +.limelight.com
  - +.lldns.net
  - +.llnw-trials.com
  - +.llnw.com
  - +.llnw.net
  - +.llnwd.net
  - +.llnwi.net
  - +.pagecdn.com
  - +.pagecdn.io
  - +.quantil.com
  - +.stackpath.com
  - +.stackpath.dev
  - +.vrcdn.cloud
  - +.vrcdn.live
  - +.vrcdn.video
  - +.ak1.net
  - +.aka-ai.com
  - +.aka-ai.net
  - +.akacrypto.net
  - +.akadeem.net
  - +.akadns.com
  - +.akadns.net
  - +.akadns6.net
  - +.akaeai.com
  - +.akafms.net
  - +.akagtm.org
  - +.akahost.net
  - +.akaint.net
  - +.akam.net
  - +.akamaa.com
  - +.akamah.com
  - +.akamak.com
  - +.akamam.com
  - +.akamai-access.com
  - +.akamai-access.net
  - +.akamai-cdn.com
  - +.akamai-platform-internal.net
  - +.akamai-platform-staging.com
  - +.akamai-platform.net
  - +.akamai-regression.net
  - +.akamai-staging.net
  - +.akamai-sucks.net
  - +.akamai-thailand.com
  - +.akamai-thailand.net
  - +.akamai-trials.com
  - +.akamai.net
  - +.akamaiedge.net
  - +.akamaientrypoint.net
  - +.akamaietpcnctest.com
  - +.akamaietpcompromisedcnctest.com
  - +.akamaietpcompromisedmalwaretest.com
  - +.akamaietpmalwaretest.com
  - +.akamaietpphishingtest.com
  - +.akamaihd-staging.net
  - +.akamaihd.com
  - +.akamaihd.net
  - +.akamaimagicmath.net
  - +.akamainewzealand.com
  - +.akamaiphillipines.com
  - +.akamaiphillipines.net
  - +.akamaitech.com
  - +.akamaitech.net
  - +.akamaitechnologies.com
  - +.akamaitechnologies.net
  - +.akamaisingapore.net
  - +.akamaistream.net
  - +.akamaized-staging.net
  - +.akamaized.net
  - +.akamaizercentral.com
  - +.akamci.com
  - +.akami.com
  - +.akami.net
  - +.akamii.com
  - +.akamqi.com
  - +.akastream.com
  - +.akastream.net
  - +.akatns.net
  - +.akstat.io
  - +.edgekey.net
  - +.edgesuite.net
  - +.iamakamai.com
  - +.iamakamai.net
  - +.soasta-dswb.com
  - +.srtcdn.net
  - +.cdn77.com
  - +.cdn77.org
  - +.fastly-edge.com
  - +.fastly-terrarium.com
  - +.fastly.com
  - +.fastly.io
  - +.fastly.net
  - +.fastlylabs.com
  - +.fastlylb.net
  - +.zencdn.net
  - +.imgix.com
  - +.imgix.net
  - +.one.one.one
  - +.akamai.co.kr
  - +.cf-china.info
  - +.cf-ns.com
  - +.cf-ns.net
  - +.cf-ns.site
  - +.cf-ns.tech
  - +.cftest5.cn
  - +.cftest6.cn
  - +.cftest7.com
  - +.cftest8.com
  - +.cloudflare-cn.com
  - +.cloudflareanycast.net
  - +.cloudflarechina.cn
  - +.cloudflarecn.net
  - +.cloudflareglobal.net
  - +.cloudflareinsights-cn.com
  - +.cloudflareperf.com
  - +.cloudflareprod.com
  - +.cloudflarestaging.com
  - +.cloudflarestoragegw.com
  - +.accdn.com.cn
  - +.akadns88.net
  - +.akadns99.net
  - +.akamai.com
  - +.akcdn.com.cn
  - +.aptdn.net
  - +.edgekey88.net
  - +.janrain.biz
  - +.janrainservices.com
  - +.skycdn.com.cn
  - +.tl88.net
